[package]
name = "storm-n-tracs-editor"
version = "0.2.1"
description = "A Tauri App"
authors = ["Nona Takahara"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "dialog-open", "dialog-save", "fs-write-file", "fs-read-file"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "^1.0"
confy = "^0.4"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
